### ISSUE TITLE
Add directories for src, test, and datasets

### ISSUE THREAD

**Issue by russellwhitaker** [brainofthestore/data-utils#3]
We'll eventually be getting into the habit of writing test coverage for our automation (e.g. unit, functional, integration, etc.) and should home source automation in `src`, test modules in `test`, and where necessary, datasets (e.g. test data fixtures) in `datasets` directories.

**Comment by george-m-shaw** [comment]
should we be checking `datasets` into this or any repo? even in the context of testing, the answer may be no. further discussion required.

**Comment by russellwhitaker** [comment]
I actually don't see a pressing need to include it at the moment, so I'll remove it.
